### ISSUE TITLE
Twitter doesn't reload script

### ISSUE THREAD

**Issue by dbeckwith** [dbeckwith/twist#1]
Clicking a link in twitter doesn't seem to reload the script, but refreshing the page or entering another twitter URL still does.

**Comment by chickenbellyfin** [comment]
There are no issues here..

**Comment by dbeckwith** [comment]
this is a legit issue dumbass

**Comment by dbeckwith** [comment]
you're an issue

**Comment by chickenbellyfin** [comment]
We will not tolerate that kind of language here.

**Comment by chickenbellyfin** [comment]
Why now

**Comment by dbeckwith** [comment]
it just bothered me that it was still open
